// Generated for: RJDev.MemoryMappedCache.Module 1.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.4.0.0
/* eslint-disable */


import './Microsoft.JavaScript.NodeApi';

declare module 'node-api-dotnet' {

	export class Client {
		constructor(tcpPort: number);

		getFileAsync(fileName: string): Microsoft.JavaScript.NodeApi.JSPromise;

		getFile(fileName: string): any;

		dispose(): void;
	}

	export namespace Module {
		export function startCacheServer(
			workingDirectory: string,
			tcpPort: number,
		): void;

		export function stopCacheServer(): void;

		export function createClient(tcpPort: number): RJDev.MemoryMappedCache.Module.Client;
	}
}
